name: "jira-rush"

services:
  app:
    container_name: jira-rush
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - nginx
    environment:
      - REGISTRATION_GITHUB_CLIENT-ID=${REGISTRATION_GITHUB_CLIENT-ID}
      - REGISTRATION_GITHUB_CLIENT-SECRET=${REGISTRATION_GITHUB_CLIENT-SECRET}
      - REGISTRATION_GITHUB_SCOPE=${REGISTRATION_GITHUB_SCOPE}
      - REGISTRATION_GOOGLE_CLIENT-ID=${REGISTRATION_GOOGLE_CLIENT-ID}
      - REGISTRATION_GOOGLE_CLIENT-SECRET=${REGISTRATION_GOOGLE_CLIENT-SECRET}
      - REGISTRATION_GOOGLE_SCOPE=${REGISTRATION_GOOGLE_SCOPE}
      - REGISTRATION_GITLAB_CLIENT-ID=${REGISTRATION_GITLAB_CLIENT-ID}
      - REGISTRATION_GITLAB_CLIENT-SECRET=${REGISTRATION_GITLAB_CLIENT-SECRET}
      - REGISTRATION_GITLAB_CLIENT-NAME=${REGISTRATION_GITLAB_CLIENT-NAME}
      - REGISTRATION_GITLAB_REDIRECT-URI=${REGISTRATION_GITLAB_REDIRECT-URI}
      - REGISTRATION_GITLAB_AUTHORIZATION-GRANT-TYPE=${REGISTRATION_GITLAB_AUTHORIZATION-GRANT-TYPE}
      - REGISTRATION_GITLAB_SCOPE=${REGISTRATION_GITLAB_SCOPE}
      - PROVIDER_GITLAB_AUTHORIZATION-URI=${PROVIDER_GITLAB_AUTHORIZATION-URI}
      - PROVIDER_GITLAB_TOKEN-URI=${PROVIDER_GITLAB_TOKEN-URI}
      - PROVIDER_GITLAB_USER-INFO-URI=${PROVIDER_GITLAB_USER-INFO-URI}
      - PROVIDER_GITLAB_USER-NAME-ATTRIBUTE=${PROVIDER_GITLAB_USER-NAME-ATTRIBUTE}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_URL=${DB_URL}

  db:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_URL=${DB_URL}
      - PGDATA=/var/lib/postgresql/data/pgdata

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf